### ISSUE TITLE
install_github() and pak() installing older version

### ISSUE THREAD

**Issue by diegotrindade** [TiagoOlivoto/pliman#5] opened 2023-06-15 10:58 UTC
Hi Tiago,

Thank you for the great work with this package. I'm trying to install its dev version, but I'm afraid that the CRAN version is being installed instead. Could you please check that? Not sure how I can make this issue reproducible, but please let me know if you can grasp something from the information provided.

Thank you in advance.

```r

devtools::install_github("TiagoOlivoto/pliman", force = TRUE)

Downloading GitHub repo TiagoOlivoto/pliman@HEAD
── R CMD build ──────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\diego\AppData\Local\Temp\RtmpIPq3a6\remotes48587a6d2613\TiagoOlivoto-pliman-e0e9c29/DESCRIPTION' ... 
─  preparing 'pliman': (3.8s)
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts (620ms)
─  checking for empty or unneeded directories
─  building 'pliman_1.1.0.9000.tar.gz'
   
Installing package into ‘C:/R/R/library’
(as ‘lib’ is unspecified)
* installing *source* package 'pliman' ...
** using staged installation
** libs
using C++ compiler: 'G__~1.EXE (GCC) 12.2.0'
using C++11
g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-43~1.0/include" -DNDEBUG  -I'C:/R/R/library/Rcpp/include' -I'C:/R/R/library/RcppArmadillo/include'   -I"C:/rtools43/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c RcppExports.cpp -o RcppExports.o
g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-43~1.0/include" -DNDEBUG  -I'C:/R/R/library/Rcpp/include' -I'C:/R/R/library/RcppArmadillo/include'   -I"C:/rtools43/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c code.cpp -o code.o
g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-43~1.0/include" -DNDEBUG  -I'C:/R/R/library/Rcpp/include' -I'C:/R/R/library/RcppArmadillo/include'   -I"C:/rtools43/x86_64-w64-mingw32.static.posix/include"  -fopenmp   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c code_polygons.cpp -o code_polygons.o
g++ -shared -s -static-libgcc -o pliman.dll tmp.def RcppExports.o code.o code_polygons.o -fopenmp -LC:/PROGRA~1/R/R-43~1.0/bin/x64 -lRlapack -LC:/PROGRA~1/R/R-43~1.0/bin/x64 -lRblas -lgfortran -lm -lquadmath -LC:/rtools43/x86_64-w64-mingw32.static.posix/lib/x64 -LC:/rtools43/x86_64-w64-mingw32.static.posix/lib -LC:/PROGRA~1/R/R-43~1.0/bin/x64 -lR
installing to C:/R/R/library/00LOCK-pliman/00new/pliman/libs/x64
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (pliman)
* 
```

```
sessionInfo()

R version 4.3.0 (2023-04-21 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22621)

Matrix products: default


locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: Europe/Tallinn
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] miniUI_0.1.1.1      jsonlite_1.8.5      compiler_4.3.0      crayon_1.5.2        promises_1.2.0.1   
 [6] Rcpp_1.0.10         stringr_1.5.0       callr_3.7.3         later_1.3.1         credentials_1.3.2  
[11] fastmap_1.1.1       mime_0.12           R6_2.5.1            curl_5.0.1          htmlwidgets_1.6.2  
[16] desc_1.4.2          profvis_0.3.8       rprojroot_2.0.3     openssl_2.0.6       shiny_1.7.4        
[21] rlang_1.1.1         cachem_1.0.8        stringi_1.7.12      httpuv_1.6.11       fs_1.6.2           
[26] sys_3.4.2           pkgload_1.3.2       memoise_2.0.1       cli_3.6.1           magrittr_2.0.3     
[31] ps_1.7.5            digest_0.6.31       processx_3.8.1      rstudioapi_0.14     xtable_1.8-4       
[36] remotes_2.4.2       devtools_2.4.5.9000 askpass_1.1         lifecycle_1.0.3     vctrs_0.6.2        
[41] prettyunits_1.1.1   glue_1.6.2          urlchecker_1.0.1    sessioninfo_1.2.2   pkgbuild_1.4.1.9000
[46] purrr_1.0.1         usethis_2.2.0       tools_4.3.0         ellipsis_0.3.2      htmltools_0.5.5 

```

**Comment by diegotrindade** [comment] 2023-06-15 11:14
Sorry. Actually, the dev version installed is 1.1.0.9. Though it should be 1.2, right?

Best,

Diego

**Comment by TiagoOlivoto** [comment] 2023-06-15 11:15
Dear @diegotrindade 
You probably have the dev version now. Check if the installed version of pliman is 1.1.0.9000. If so, this is the last one. 
Since this is not a bug, I'm closing now. Feel free to email me if you need more information.
Best

**Closed by TiagoOlivoto** 2023-06-15 11:15 UTC

**Comment by diegotrindade** [comment] 2023-06-15 11:19
Ok. I misunderstood then. I thought the current dev version was the 1.2.

I'm having some bugs related to version 1.1.0.9, but I'll open another issue at some point.

Thank you! 

Best
